import Head from "next/head";
import { FC, PropsWithChildren, use } from "react";
import NavBar from "../ui/NavBar";
import { useRouter } from "next/router";
interface Props {
  title?: string;
}

//debemos configurar de esta manera cuando estamos haciendolo del lado del frontend

const origin = (typeof window === 'undefined'?'':window.location.origin)

const Layout = ({ children, title }: PropsWithChildren<Props>) => {
  console.log({origin
  })

  
  return (
    <>
      <Head>
        <title>{title || "Pokemon App"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <meta property="og:title" content={`Informacion sobre ${title}`} />
        <meta
          property="og:description"
          content={`esta es la pagina sobre${title}`}
        />
        <meta
          property="og:image"
          content={`${origin}/img/banner.png`}
        />
      </Head>
      <NavBar />


      <main
        style={{
          padding: "0px 20px",
        }}
      >
        {children}
      </main>
    </>
  );
};

export default Layout;
